# Generated by Django 3.0.5 on 2020-05-22 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20200521_1932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='breakfast',
            old_name='b_items',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='dinner',
            old_name='d_items',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='lunch',
            old_name='l_items',
            new_name='item',
        ),
    ]
